name: CI
run-name: ${{ github.head_ref || github.ref_name }} · CI

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: write
      checks: write
      contents: read
      pull-requests: write
      statuses: write

    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true

      - uses: godot-gdunit-labs/gdUnit4-action@v1
        with:
          godot-version: '4.7'
          version: installed
          paths: 'res://tests/'
          timeout: 5
          report-name: test_report.xml
